name: crypto_font_icons
description: CryptoFont Icons by https://cryptofont.com/#icons for Flutter
version: 1.0.1
homepage: https://www.github.com/casabian/cryptofont-flutter

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

flutter:
  fonts:
    - family: CryptoFont
      fonts:
        - asset: font/cryptofont-webfont.ttf
